/**
 * Challenge catalog derived from the product challenge PDF.
 * Personalization uses `trigger` + runtime user context.
 */

export type ChallengeCategory =
  | "collection"
  | "scan"
  | "care"
  | "landscape"
  | "explore";

export type ChallengeRepeat = "once" | "daily";

export type ChallengeEventType =
  | "plant_added"
  | "care_completed"
  | "scan_completed"
  | "landscape_created"
  | "care_routine_viewed"
  | "compare_scan_completed";

export interface ChallengeDefinition {
  code: string;
  title: string;
  description: string;
  points: number;
  category: ChallengeCategory;
  repeat: ChallengeRepeat;
  /** Default progress target (e.g. scan 2 plants today → 2). */
  target: number;
  /** Events that can advance this challenge. */
  events: ChallengeEventType[];
  /** Soft priority; higher = preferred when selecting daily set. */
  priority: number;
}

export const DAILY_CHALLENGE_COUNT = 1;

export const CHALLENGE_CATALOG: ChallengeDefinition[] = [
  // ── Collection / plants ───────────────────────────────────────────────────
  {
    code: "ADD_FIRST_PLANT",
    title: "Add your first plant",
    description: "Add a plant to your garden to get started.",
    points: 2,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 100,
  },
  {
    code: "ADD_2_PLANTS",
    title: "Add 2 plants to your garden",
    description: "Grow your collection to at least 2 plants.",
    points: 2,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 90,
  },
  {
    code: "ADD_5_PLANTS",
    title: "Add 5 plants to your garden",
    description: "Reach 5 plants in your garden.",
    points: 3,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 80,
  },
  {
    code: "ADD_10_PLANTS",
    title: "Add 10 plants to your garden",
    description: "Reach 10 plants in your garden.",
    points: 4,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 70,
  },
  {
    code: "ADD_INDOOR_PLANT",
    title: "Add an indoor plant",
    description: "Add a plant suited for indoor spaces.",
    points: 1,
    category: "collection",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 60,
  },
  {
    code: "ADD_BALCONY_PLANT",
    title: "Add a balcony-friendly plant",
    description: "Add a plant that thrives on a balcony.",
    points: 1,
    category: "collection",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 60,
  },
  {
    code: "ADD_OUTDOOR_PLANT",
    title: "Add an outdoor plant",
    description: "Add a plant suited for outdoor spaces.",
    points: 1,
    category: "collection",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 60,
  },
  {
    code: "ADD_LOW_MAINTENANCE",
    title: "Add a low-maintenance plant",
    description: "Add an easy-care plant that matches a beginner profile.",
    points: 2,
    category: "collection",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 65,
  },
  {
    code: "ADD_FLOWERING",
    title: "Add a flowering plant",
    description: "Add a flowering plant to your collection.",
    points: 2,
    category: "collection",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 55,
  },
  {
    code: "ADD_LEAFY",
    title: "Add a leafy plant",
    description: "Add a leafy plant to your collection.",
    points: 2,
    category: "collection",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 55,
  },
  {
    code: "MINI_GARDEN_3",
    title: "Build your first mini garden",
    description: "Own at least 3 plants to form a mini garden.",
    points: 3,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 75,
  },
  {
    code: "GARDEN_15",
    title: "Grow your garden to 15 plants",
    description: "Expand your garden to 15 plants.",
    points: 5,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 50,
  },
  {
    code: "GARDEN_25",
    title: "Grow your garden to 25 plants",
    description: "Expand your garden to 25 plants.",
    points: 6,
    category: "collection",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 45,
  },

  // ── Scans ─────────────────────────────────────────────────────────────────
  {
    code: "FIRST_SCAN",
    title: "Complete your first plant scan",
    description: "Scan a plant to check its health.",
    points: 5,
    category: "scan",
    repeat: "once",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 95,
  },
  {
    code: "SCAN_OWNED",
    title: "Scan a plant from your garden",
    description: "Scan one of the plants you already own.",
    points: 4,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 70,
  },
  {
    code: "SCAN_2_TODAY",
    title: "Scan 2 plants today",
    description: "Complete 2 plant scans today.",
    points: 5,
    category: "scan",
    repeat: "daily",
    target: 2,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 72,
  },
  {
    code: "SCAN_3_DIFFERENT",
    title: "Scan 3 different plants",
    description: "Scan 3 different plants in your collection journey.",
    points: 6,
    category: "scan",
    repeat: "once",
    target: 3,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 58,
  },
  {
    code: "CHECK_UNHEALTHY",
    title: "Check on an unhealthy plant",
    description: "Re-check a plant that previously looked unhealthy.",
    points: 4,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 78,
  },
  {
    code: "FOLLOW_UP_ISSUE",
    title: "Follow up on {issue}",
    description: "Follow up on a previous diagnosis issue.",
    points: 6,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 82,
  },
  {
    code: "RESCAN_AFTER_7_DAYS",
    title: "Re-scan a plant after 7 days",
    description: "Re-scan a plant you scanned a week or more ago.",
    points: 6,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 68,
  },
  {
    code: "COMPARE_PROGRESS",
    title: "Compare your plant's progress",
    description: "Run a compare scan against a previous diagnosis.",
    points: 5,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["compare_scan_completed"],
    priority: 74,
  },
  {
    code: "SCAN_NOT_RECENT",
    title: "Scan a plant you haven't checked recently",
    description: "Scan a plant that has not been checked lately.",
    points: 4,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 62,
  },
  {
    code: "SCAN_UNUSUAL_SYMPTOMS",
    title: "Check a plant showing unusual symptoms",
    description: "Scan a plant that may show unusual symptoms.",
    points: 5,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 64,
  },
  {
    code: "COMPLETE_5_SCANS",
    title: "Complete 5 successful scans",
    description: "Reach 5 successful plant scans.",
    points: 5,
    category: "scan",
    repeat: "once",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 56,
  },
  {
    code: "CHECK_PLANT_IMPROVED",
    title: "Check whether {PlantName} improved",
    description: "Re-scan a previously diagnosed plant to see if it improved.",
    points: 5,
    category: "scan",
    repeat: "daily",
    target: 1,
    events: ["scan_completed", "compare_scan_completed"],
    priority: 80,
  },

  // ── Care ──────────────────────────────────────────────────────────────────
  {
    code: "FIRST_CARE",
    title: "Complete your first plant care activity",
    description: "Water, fertilize, prune, or care for a plant once.",
    points: 2,
    category: "care",
    repeat: "once",
    target: 1,
    events: ["care_completed"],
    priority: 96,
  },
  {
    code: "CARE_2_TODAY",
    title: "Complete 2 care activities today",
    description: "Finish 2 care tasks today.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 2,
    events: ["care_completed"],
    priority: 85,
  },
  {
    code: "CARE_5_TOTAL",
    title: "Complete 5 care activities",
    description: "Reach 5 completed care activities overall.",
    points: 3,
    category: "care",
    repeat: "once",
    target: 1,
    events: ["care_completed"],
    priority: 66,
  },
  {
    code: "CHECK_CARE_ROUTINE",
    title: "Check your plant care routine",
    description: "Open your care reminders and review upcoming tasks.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_routine_viewed"],
    priority: 50,
  },
  {
    code: "CARE_OLDEST",
    title: "Care for your oldest plant",
    description: "Complete a care task for the plant you added first.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 58,
  },
  {
    code: "CARE_NEWEST",
    title: "Care for your newest plant",
    description: "Complete a care task for your most recently added plant.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 58,
  },
  {
    code: "CARE_NEGLECTED",
    title: "Check a plant you haven't cared for recently",
    description: "Give attention to a plant that has not been cared for lately.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 67,
  },
  {
    code: "WATERING_ROUTINE",
    title: "Complete your watering routine",
    description: "Complete a watering task for one of your plants.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 76,
  },
  {
    code: "FOLLOW_WATERING_FREQ",
    title: "Follow your {wateringFrequency} routine",
    description: "Complete watering according to your onboarding preference.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 73,
  },
  {
    code: "ATTENTION_3_PLANTS",
    title: "Give attention to 3 plants",
    description: "Complete care activities for 3 different plants today.",
    points: 3,
    category: "care",
    repeat: "daily",
    target: 3,
    events: ["care_completed"],
    priority: 69,
  },
  {
    code: "TODAYS_CARE",
    title: "Complete today's plant care",
    description: "Complete at least one due care task today.",
    points: 1,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 88,
  },
  {
    code: "MAINTAIN_STREAK",
    title: "Maintain your care streak",
    description: "Complete a care activity to keep your streak alive.",
    points: 2,
    category: "care",
    repeat: "daily",
    target: 1,
    events: ["care_completed"],
    priority: 84,
  },

  // ── Landscape ─────────────────────────────────────────────────────────────
  {
    code: "FIRST_LANDSCAPE",
    title: "Create your first landscape design",
    description: "Generate your first garden landscape design.",
    points: 7,
    category: "landscape",
    repeat: "once",
    target: 1,
    events: ["landscape_created"],
    priority: 92,
  },
  {
    code: "DESIGN_SPACE_TYPE",
    title: "Design your {spaceType}",
    description: "Create a design for the space type from your survey.",
    points: 5,
    category: "landscape",
    repeat: "daily",
    target: 1,
    events: ["landscape_created"],
    priority: 70,
  },
  {
    code: "DESIGN_OUTDOOR",
    title: "Create an outdoor landscape design",
    description: "Generate an outdoor garden design.",
    points: 5,
    category: "landscape",
    repeat: "daily",
    target: 1,
    events: ["landscape_created"],
    priority: 63,
  },
  {
    code: "DESIGN_INDOOR",
    title: "Create an indoor garden design",
    description: "Generate an indoor garden design.",
    points: 5,
    category: "landscape",
    repeat: "daily",
    target: 1,
    events: ["landscape_created"],
    priority: 63,
  },
  {
    code: "DESIGN_BALCONY",
    title: "Create a balcony garden design",
    description: "Generate a balcony garden design.",
    points: 5,
    category: "landscape",
    repeat: "daily",
    target: 1,
    events: ["landscape_created"],
    priority: 63,
  },
  {
    code: "DESIGN_TO_REAL_GARDEN",
    title: "Turn your design into a real garden",
    description: "Add a plant after creating a landscape design.",
    points: 7,
    category: "landscape",
    repeat: "once",
    target: 1,
    events: ["plant_added"],
    priority: 71,
  },
  {
    code: "IMPROVE_DESIGN",
    title: "Improve your existing garden design",
    description: "Create another design to improve your garden plan.",
    points: 5,
    category: "landscape",
    repeat: "daily",
    target: 1,
    events: ["landscape_created"],
    priority: 54,
  },
  {
    code: "EXPLORE_NEW_CATEGORY",
    title: "Explore a new plant category",
    description: "Add a plant from a category you do not already own.",
    points: 3,
    category: "explore",
    repeat: "daily",
    target: 1,
    events: ["plant_added"],
    priority: 52,
  },
];

export const CHALLENGE_BY_CODE: Record<string, ChallengeDefinition> =
  Object.fromEntries(CHALLENGE_CATALOG.map((c) => [c.code, c]));
